[package]
name = "fm-transcripts-exclude-timestamp"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
ezio = "0.1.2"